### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by tiagojsag** [nerik/Leaflet.Emoji#1] opened 2017-01-23 20:48 UTC
![image](https://cloud.githubusercontent.com/assets/973964/22222014/8e7c3086-e1b5-11e6-9464-8d76cd5836b1.png)

**Comment by tiagojsag** [comment] 2017-01-23 20:48
Also, scrolling up and down moves the emoji layer up and down

**Comment by nerik** [comment] 2017-01-26 18:58
The vertical offset should be fixed in latest release. 
Still pondering about how to fix the horizontal offset problem.
Can't reproduce the scrolling issue for now.

**Closed as completed** 2018-07-22 14:49 UTC
